@startuml
'https://plantuml.com/class-diagram

interface AuthenticationConverter
class OAuth2AuthorizationCodeRequestAuthenticationConverter
class OAuth2DeviceAuthorizationConsentAuthenticationConverter
class OAuth2TokenExchangeAuthenticationConverter
class OAuth2RefreshTokenAuthenticationConverter


AuthenticationConverter <|.. OAuth2AuthorizationCodeRequestAuthenticationConverter
AuthenticationConverter <|.. OAuth2DeviceAuthorizationConsentAuthenticationConverter
AuthenticationConverter <|.. OAuth2TokenExchangeAuthenticationConverter
AuthenticationConverter <|.. OAuth2RefreshTokenAuthenticationConverter


@enduml