@startuml
'https://plantuml.com/class-diagram

class InMemoryRegisteredClientRepository
class JdbcRegisteredClientRepository
interface RegisteredClientRepository

RegisteredClientRepository <|.. InMemoryRegisteredClientRepository
RegisteredClientRepository <|.. JdbcRegisteredClientRepository

@enduml