@startuml
'https://plantuml.com/sequence-diagram

autonumber

用户 -> 第三方应用: 发起授权登录
第三方应用 -> 前端服务器: 请求授权页面
前端服务器 -> 授权服务器: GET请求授权页面: /oauth2/authorize
前端服务器 <-- 授权服务器: 无权限
用户 <-- 前端服务器: 返回登录界面
用户 -> 前端服务器: 登录
前端服务器 -> 授权服务器: 调用/login接口
授权服务器 -> 授权服务器: 执行登录
前端服务器 <-- 授权服务器: 返回登录token
第三方应用 <-- 前端服务器: 返回登录token
第三方应用 -> 前端服务器: 重新发起（携带登录token），请求授权页面
前端服务器 -> 授权服务器: 重新发起（携带登录token），GET请求授权页面: /oauth2/authorize
前端服务器 <-- 授权服务器: 返回授权信息
用户 <-- 前端服务器: 返回授权页面
用户 -> 前端服务器: 确认授权
前端服务器 -> 授权服务器: POST请求确认授权: /oauth2/authorize
前端服务器 <-- 授权服务器: 返回授权码code
第三方应用 <-- 前端服务器: 通过客户端配置的调整uri，返回授权码code
第三方应用 -> 授权服务器: POST请求获得access_token: /oauth2/token
第三方应用 <-- 授权服务器: 返回access_token
第三方应用 -> 资源服务器: 请求资源
第三方应用 <-- 资源服务器: 返回资源

@enduml